version: 2.1

jobs:
  sshx-job:
    docker:
      - image: ubuntu:latest
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Cập nhật và cài đặt gói
          command: |
            apt-get update && apt-get upgrade -y
            apt-get install -y htop curl ca-certificates git unzip wget python3
            rm -rf /var/lib/apt/lists/*
      - run:
          name: Chạy SSHX
          command: curl -sSf https://sshx.io/get | sh -s run
      - run:
          name: Keep container alive
          command: tail -f /dev/null

workflows:
  version: 2
  main:
    jobs:
      - sshx-job